import tempfile
import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from weasyprint import HTML

class ReportGenerator:
    @staticmethod
    def create_pdf_report(gross: float, tax_saved: float, optimal_mix: dict, advice: str) -> bytes:
        """
        Creates a PDF Action Plan using ReportLab.
        Returns the raw PDF bytes.
        """
        fd, path = tempfile.mkstemp(suffix=".pdf")
        os.close(fd)
        
        c = canvas.Canvas(path, pagesize=letter)
        c.setFont("Helvetica-Bold", 20)
        c.drawString(100, 750, "Hyper-Personalized AI Tax Strategy")
        
        c.setFont("Helvetica", 14)
        c.drawString(100, 710, f"Gross Income: Rs {gross:,.2f}")
        c.drawString(100, 680, f"Estimated Tax Saved: Rs {tax_saved:,.2f}")
        
        c.setFont("Helvetica-Oblique", 14)
        c.drawString(100, 640, "Recommended Investment Mix (March 31 Deadline):")
        
        c.setFont("Helvetica", 12)
        y = 610
        for inst, amt in optimal_mix.items():
            if amt > 0:
                c.drawString(120, y, f"- {inst}: Rs {amt:,.2f}")
                y -= 25
                
        c.drawString(100, y - 20, "AI Advisory Statement:")
        textobject = c.beginText(100, y - 45)
        textobject.setFont("Helvetica", 10)
        # Reportlab does not auto-wrap drawString, simple text layout
        for line in advice.split("\n"):
            textobject.textLine(line[:100]) # naive wrap
        c.drawText(textobject)
        
        c.save()
        
        with open(path, "rb") as f:
            pdf_bytes = f.read()
        os.remove(path)
        return pdf_bytes

    @staticmethod
    def create_whatsapp_card(tax_saved: float, optimal_mix: dict) -> bytes:
        """
        Creates a mobile-friendly shareable image card using WeasyPrint (HTML to Image/PDF).
        """
        html_content = f"""
        <html>
        <body style="font-family: sans-serif; background: #1e1e2f; color: white; padding: 20px; width: 400px; border-radius: 12px;">
            <h2 style="color: #4ECDC4;">Tax Strategy Active ⚡</h2>
            <p><strong>Projected Savings:</strong> Rs {tax_saved:,.2f}</p>
            <hr style="border-color: #333;" />
            <ul style="list-style: none; padding-left: 0;">
                {"".join([f'<li style="margin-bottom: 10px; background: #2f2a40; padding: 10px; border-radius: 8px;"><strong>{k}</strong><br/>Rs {v:,.2f}</li>' for k,v in optimal_mix.items() if v > 0])}
            </ul>
            <p style="font-size: 10px; color: #888; text-align: center;">Generated by Hyper-Personalized AI Tax Optimizer</p>
        </body>
        </html>
        """
        # We process as PDF for simplicity, could use png format with WeasyPrint later if desired
        pdf_bytes = HTML(string=html_content).write_pdf()
        return pdf_bytes
